### ISSUE TITLE
Import paths seem to be wrong in windows

### ISSUE THREAD

**Issue by Ado77** [Polymer/vscode-plugin#9] opened 2016-10-18 10:27 UTC
I installed the sample app from github.com/Polymer/vscode-plugin.git and the the example src code throws this out.

[polymer] Unable to load import: ENOENT: no such file or directory, open '**c:\c:**\dev\Personal\vscode-plugin\client\paper-button\paper-button.html'

![vs code poly ide](https://cloud.githubusercontent.com/assets/5011870/19474050/a812fc4c-9579-11e6-9e38-468d03a4486b.PNG)

**Comment by benhjt** [comment] 2016-10-18 10:30
Same issue here. I have generated the starter-kit from the polymer-cli project. When I go into `/src/my-app.html`, none of the bower components are recognised and I get the following error:

> [polymer] Unable to load import: ENOENT: no such file or directory, open 'c:\c:\Users\USERNAME\Downloads\test-app\bower_components\polymer\polymer.html'

If I `CTRL + Click` on the import, it does navigate to the import file. I also get the same error for elements in the same `/src/` directory:

> [polymer] Unable to load import: ENOENT: no such file or directory, open 'c:\c:\Users\USERNAME\Downloads\test-app\src\my-icons.html'

**Comment by LostInBrittany** [comment] 2016-10-18 10:54
I have also the same message, and the same weird `c:\c:\` path in the error message, yeah

**Comment by tobiashutterer** [comment] 2016-10-18 13:37
Same here. Windows 10. 
The error occurs for the general apps file structure and for element. 

app
![image](https://cloud.githubusercontent.com/assets/8007595/19479715/5ac8d334-9548-11e6-92a2-d620d5b7c487.png)

element
![image](https://cloud.githubusercontent.com/assets/8007595/19479775/a9093f48-9548-11e6-87cc-db64ca1f82dc.png)

**Comment by rictic** [comment] 2016-10-18 13:48
Yeah, this is a bug in either the analyzer or the editor service. The new analyzer hasn't been tested in Windows yet :X

**Comment by rictic** [comment] 2016-10-18 13:49
I've got a Windows machine back home, will try to take a look around Sunday. Until then, PRs very welcome!

**Comment by quangld** [comment] 2016-10-18 16:27
The bug is in the **getWorkspacePathToFile** function in 
%USERPROFILE%\.vscode\extensions\polymer.polymer-ide-0.1.0\server\server.js

```
function getWorkspacePathToFile(doc) {
    const match = doc.uri.match(/^file:\/\/(.*)/);
    if (!match || !match[1] || !workspaceRoot) {
        return undefined;
    }
    match[1] = match[1].replace(/^\/(\D)(\%3A\/)/,'$1:/')     //correct the problem in Windows path
    return path.relative(workspaceRoot, match[1]);
}
```

**Comment by rikwilbrink** [comment] 2016-10-18 16:34
Not really quangId

its in polymer-analyzer/src/url-loader/fs-url-loader.ts

> 
>   getFilePath(url: string): string {
>     let urlObject = parseUrl(url);
>     let pathname =
>         pathlib.normalize(decodeURIComponent(urlObject.pathname || ''));
>     if (!this._isValid(urlObject, pathname)) {
>       throw new Error(`Invalid URL ${url}`);
>     }
>
>    return this.root ? pathlib.join(this.root, pathname) : pathname;
>  }

this adds a c:\ in front of the pathname.
pathlib.join(this.root, pathname) 

all the params during the process: 
 url = ..\c%3A\Users\[snip]\public\bower_components\webcomponentsjs\webcomponents-lite.js 
 urlObject.pathname = ..\c%3A\Users\[snip]\public\bower_components\webcomponentsjs\webcomponents-lite.js 
 pathname = ..\c:\Users\[snip]\public\bower_components\webcomponentsjs\webcomponents-lite.js 
 this.root = c:\Users\[snip] 
 pathlib.join = c:\c:\Users\[snip]\public\bower_components\webcomponentsjs\webcomponents-lite.js 

So doing a slice(3) helped me out in my situation. obviously not the perfect solution

**Comment by quangld** [comment] 2016-10-18 16:44
Have you tried my solution?
polymer-analyzer is a dependent package.
It's better to fix it in this vscode-plugin package

**Comment by rikwilbrink** [comment] 2016-10-18 16:48
Analyser is a stand alone package in this case, so i expect the same problem to occur there.

**Comment by quangld** [comment] 2016-10-18 17:03
rikwilbrink:
I think the problem is the %3A in the url, 
if the url passed to getFilePath already contains %3A, then the root of this problem is not in getFilePath

**Comment by rikwilbrink** [comment] 2016-10-18 17:27
The encoded part is not the problem, check what the pathname variable in my post.

I will concede however that the '../' var at the start  might fall in the category 'garbage in' but I'm not experienced enough to state this as a fact.

**Comment by quangld** [comment] 2016-10-18 18:58
Finally, I was able to track down the cause. Whenever a file's content is changed, it calls onDidChangeContent function in the extension and passes a document object to it. This object has uri property, which is the uri of the document. This uri needs to be parsed properly before used. I need more time to check on getFilePath function. In the mean while, here is my suggestion to fix, will try to do PR later

```
function getWorkspacePathToFile(doc) {
    const match = decodeURIComponent(doc.uri).match(/^file:\/{2,3}(.*)/); //fixed problem with windows' file path
    if (!match || !match[1] || !workspaceRoot) {
        return undefined;
    }
    return path.relative(workspaceRoot, match[1]);
}
```

**Comment by rictic** [comment] 2016-10-19 12:26
Also related: https://github.com/Polymer/polymer-editor-service/issues/7

Apologies on missing this. Is anyone aware of a nodejs continuous integration service like travis that can test on windows?

**Comment by pomber** [comment] 2016-11-07 17:25
Any workaround?

**Comment by rictic** [comment] 2016-11-07 17:29
This should have been fixed by https://github.com/Polymer/vscode-plugin/commit/eeada315ceb7f2bf5c95eb45e1e0a1d0d91cbda8

The only windows bug I'm aware of that's open right now is #35 

If you're still seeing this behavior with >v0.1.2 please file a new issue and I'll take a look.

**Closed by rictic** 2016-11-07 17:29 UTC

**Comment by yveslange** [comment] 2017-08-30 08:49
Hi @rictic, I'm still facing this issue. I created an app using the app-template of Polymer 2.0.

```
bower_components/
build/
src/
-- my-app/
---- my-app.html
---- my-page.html
```

In `my-app/my-app.html`, I'm importing `../../bower_components/app-route/app-location.html`. 
```html
<link rel="import" href="../../bower_components/polymer/polymer-element.html">
<link rel="import" href="../../bower_components/app-route/app-location.html">
```

Polymer lint reclaims that it was `unable to load import`. But `app-location.html` exists in bower_components/. 


polymer lint error: 
```sh
error:   Promise rejection: Error: 8 error(s) occurred during build.
error:   Error: 8 error(s) occurred during build.
    at BuildAnalyzer._done (C:\Users\LangeY\scoop\persist\nodejs\bin\node_modules\polymer-cli\node_modules\polymer-build\lib\analyzer.js:265:36)
    at BuildAnalyzer.<anonymous> (C:\Users\LangeY\scoop\persist\nodejs\bin\node_modules\polymer-cli\node_modules\polymer-build\lib\analyzer.js:225:26)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\LangeY\scoop\persist\nodejs\bin\node_modules\polymer-cli\node_modules\polymer-build\lib\analyzer.js:17:58)
    at <anonymous>
```

**Setup**: windows 10, visual-code, polymer-cli 1.5.2

Anything that would help ?
