### ISSUE TITLE
polymer-ide does not work for some projects

### ISSUE THREAD

**Issue by nguyenhuedang** [Polymer/vscode-plugin#48] opened 2017-02-24 06:48 UTC
Since update, the IDE does not response any suggest about attributes completions or document, I also can not jump to any component by ⌘ + click any more. I have try on both my Mac & my teammate's one, with many different project as well.
Is it a bug? Thank you.

**Comment by rictic** [comment] 2017-02-24 14:55
Hm, interesting, autocompletions and jump to element definition are working for me on my mac. Do you see any errors in the plugin's output window? Press cmd-shift-u to bring up the output window and select vscode-plugin in the dropdown (if it's present).

A few other things to confirm:
  - what version of vscode are you using?
  - what version of os x?
  - do you get diagnostics from the plugin? for example, if you have an html import like `<link rel="import" href="does-not-exist.html">` is the url underlined in red?

**Comment by tony19** [comment] 2017-02-25 22:48
This also happens for me.

### Steps to reproduce

1. Use polymer-cli to generate starter-kit project
2. Open project in VS Code, then open  `my-app.html`
3. Hold <kbd>⌘</kbd> and click on `<my-view>` at line 94.

### Expected Behavior
VS Code opens `my-view1.html` (and jumps to the Polymer declaration).

### Actual Behavior
Nothing happens.

### Environment
 * macOS Sierra 10.12
 * VS Code 1.9.1
 * polymer-ide 0.4.0

**Comment by tony19** [comment] 2017-02-25 22:50
> do you get diagnostics from the plugin? for example, if you have an html import like <link rel="import" href="does-not-exist.html"> is the url underlined in red?

@rictic Nope. No red underlines.

**Comment by tony19** [comment] 2017-02-25 23:04
The interesting thing is the plugin works fine for the `application` template from polymer-cli, but not the `starter-kit` or `shop`.

**Comment by rictic** [comment] 2017-02-25 23:51
Awesome, thanks for the repro steps! I can reproduce this.

**Comment by rictic** [comment] 2017-02-27 14:26
Ok, I've isolated the bug. We're using the STDIO transport for communicating between vscode and the plugin. This is all good, except that we shouldn't do any logging to stdout or stderr, or it will disrupt that communications channel. If this happens when the plugin is first booting up the observed behavior is that the plugin will fail to start.

The warning that's being logged for `starter-kit` is due to using `sourceGlobs` and `includeDependencies` in `polymer.json`. A work around for this specific issue is to rename those fields in your polymer.json to their new names `sources` and `extraDependencies`.

I'm taking a look now at what we can do to prevent this class of bug.

**Comment by rictic** [comment] 2017-02-28 20:52
Huh, the github regex for when a commit fixes an issue is more sensitive than I thought.

**Comment by rictic** [comment] 2017-03-04 04:00
The fix for this issue was just published in v0.4.2

**Comment by tony19** [comment] 2017-03-04 04:06
@rictic Hmm, I'm still able to reproduce the bug in v0.4.2, using the [steps I listed above](https://github.com/Polymer/vscode-plugin/issues/48#issuecomment-282518293). Is it working for you?

**Comment by rictic** [comment] 2017-03-04 04:08
Hm, you know, I tested my minimal repro but not the full starter-kit template.

**Comment by rictic** [comment] 2017-03-04 04:13
Can confirm that the issue isn't fixed. Interesting.

**Comment by tony19** [comment] 2017-03-10 17:11
@rictic Just installed everything anew on a laptop, and it seems to be working correctly.

**Comment by rictic** [comment] 2017-03-20 22:50
I can repro some super slow flakiness on polymer-1-starter-kit. I get some lint warnings, slowly and gradually, but it seems like something in psk 1 is triggering some pathological slowness/weirdness. Needs more investigation.

**Closed** 2018-04-11 02:32 UTC
