### ISSUE TITLE
'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by tony19** [Polymer/vscode-plugin#44] opened 2017-01-13 16:53 UTC
I'm getting this error in my ES6 projects for all `import`s. I'm guessing it's a config issue specific to `polymer-ide` because it compiles without this warning and runs fine. How can I fix this?

![screen shot 2017-01-13 at 10 50 48 am](https://cloud.githubusercontent.com/assets/26580/21937815/4c52948c-d97e-11e6-812a-aa871a89f6ea.png)

### Environment

 * macOS Sierra
 * VS Code 1.8.1
 * polymer-ide 0.2.0

**Comment by rictic** [comment] 2017-01-13 22:09
Thanks for filing this issue! I've got a fix for this issue out for review.

Closing this issue as duplicate of https://github.com/Polymer/polymer-editor-service/issues/12 - follow updates there.

**Closed by rictic** 2017-01-13 22:09 UTC
